package com.appdev.smartkisan.presentation.navigation

sealed class Routes(val route: String) {
    object ResetPassword : Routes("reset_password")
    object ResetPasswordConfirmation : Routes("reset_confirmation")
    object OnBoarding : Routes("OnBoarding_Screen")
    object RoleSelect : Routes("RoleSelect_Screen")
    object SignUp : Routes("SignUp_Screen")
    object Login : Routes("Login_Screen")
    object PasswordReset : Routes("PasswordReset_Screen")
    object OtpInput : Routes("OtpInput_Screen")
    object HomeScreen : Routes("Home_Screen")
    object AccountScreen : Routes("Account_Screen")
    object MarketPlace : Routes("MarketPlace_Screen")
    object PlantDisease : Routes("PlantDisease_Screen")
    object ImageCropper : Routes("cropper_screen")
    object DiagnosisResult : Routes("DiagnosisResult_Screen")
    object NewsList : Routes("News_Screen")
    object ShopsOnMap : Routes("Map_Screen")
    object NewsDetails : Routes("NewsDetails_Screen")
    object UserInfo : Routes("UserInfo_Screen")
    object ChatBotScreen : Routes("ChatBot_Screen")
    object ProductDetailScreen : Routes("ProductDetail_Screen")
    object UserChatListScreen : Routes("UserChatList_Screen")
    object Main : Routes("Main_Screen")
    object SellerMain : Routes("SellerMain_Screen")
    object SellerHomeScreen : Routes("SellerHome_Screen")
    object SellerInboxScreen : Routes("SellerInbox_Screen")
    object ChatInDetailScreen : Routes("ChatDetail_Screen")
    object StoreManagementScreen : Routes("StoreManagement_Screen")
    object AddProductScreen : Routes("AddProduct_Screen")
    object SellerAccountScreen : Routes("SellerAccount_Screen")
}

